### ISSUE TITLE
建议加个自定义提示语

### ISSUE THREAD

**Issue by LazuliKao** [05007/land-g7#1]
建议加个自定义提示语，或者配置文件加些

比如由于修改的UI，菜单界面文字会很瞎
![image](https://user-images.githubusercontent.com/46601807/88015905-e3eef080-cb54-11ea-9d47-29dbcc303de9.png)

也许不加颜色符号看起来更好点
![image](https://user-images.githubusercontent.com/46601807/88016007-14368f00-cb55-11ea-94ff-971fe0e24fb9.png)

**Comment by 05007** [comment]
自定义文本的话，稍微等一段时间吧，我先把所有基础功能都完善了

**Comment by littlegao233** [comment]
顶顶
